In [1]:
import pandas as pd
from functools import reduce
import statsmodels.api as sm
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("data/IL_public_data.csv").iloc[:, 1:]

,UNITID,DVADM01,DVADM02,DVADM03,DVADM04,DVADM05,DVADM06,DVADM07,DVADM08,DVADM09,...,DVIC13,F3GOVTPC,F3GOVTFT,F3AISSFT,F3AISSPC,TFTESTF,IRPSSTF,ADMNSTF,OPRFSTF,NONPSTF
0,144005,63.0,59.0,65.0,10.0,11.0,9.0,9.0,10.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,144892,53.0,50.0,54.0,20.0,22.0,18.0,20.0,22.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,145336,46.0,43.0,47.0,35.0,40.0,33.0,35.0,40.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,145600,73.0,70.0,75.0,27.0,29.0,25.0,27.0,28.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,145637,59.0,54.0,65.0,30.0,31.0,29.0,30.0,31.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#drop any column that has almost 40% missing values
res2 = df.columns[df.isnull().sum() > 47]
df.drop(res2, inplace=True, axis=1)
df.set_index(['year', 'UNITID'], inplace=True)

In [4]:
df.isna().sum().sum()

1802

In [5]:
# #Getting rid of Governors State, because it is missing graduation rates
# df = df[df["UNITID"] != 145336]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 120 entries, (2019, 144005) to (2010, 149772)
Columns: 203 entries, ENRTOT to DOCDEGOT
dtypes: float64(203)
memory usage: 191.4 KB

In [7]:
df.describe()

,ENRTOT,FTE,ENRFT,ENRPT,PCTENRWH,PCTENRBK,PCTENRHS,PCTENRAP,PCTENRAS,PCTENRNH,...,SASCDEG,SBAMACRT,SCERT24,SCERT1,UNDUP,UNDUPUG,FTE12MN,DOCDEGRS,DOCDEGPP,DOCDEGOT
count,120.000000,120.000000,120.00000,120.000000,120.0000,120.000000,120.000000,120.000000,120.000000,120.0,...,96.000000,96.000000,96.000000,96.0,120.000000,120.000000,120.000000,108.000000,108.000000,108.000000
mean,16035.108333,14009.891667,12761.25000,3273.858333,53.4250,18.783333,10.708333,5.316667,5.258333,0.0,...,7.177083,33.416667,0.135417,0.0,18411.358333,13333.075000,15164.166667,124.685185,124.138889,1.824074
std,11779.025065,11311.346914,11071.20192,1282.241763,20.0049,18.045779,7.981487,5.404610,5.363267,0.0,...,24.396719,37.265383,0.828693,0.0,12196.548407,8435.054202,12844.086191,228.170483,185.485544,5.859458
min,2964.000000,2258.000000,1810.00000,1154.000000,5.0000,5.000000,3.000000,1.000000,1.000000,0.0,...,0.000000,0.000000,0.000000,0.0,3593.000000,2438.000000,2260.000000,0.000000,0.000000,0.000000
25%,7273.000000,5533.000000,4326.25000,2334.500000,41.0000,9.000000,6.000000,2.000000,2.000000,0.0,...,0.000000,9.000000,0.000000,0.0,8967.500000,6749.500000,5798.750000,1.000000,0.000000,0.000000
50%,12569.500000,11159.500000,10127.00000,3047.500000,60.0000,13.000000,8.000000,3.000000,2.500000,0.0,...,0.000000,26.000000,0.000000,0.0,14822.500000,11891.000000,11345.500000,10.000000,37.000000,0.000000
75%,20719.500000,19132.750000,17923.50000,4143.500000,69.0000,17.000000,11.250000,6.500000,6.500000,0.0,...,0.000000,44.000000,0.000000,0.0,23300.750000,18317.250000,18871.500000,137.750000,168.750000,0.000000
max,51605.000000,46818.000000,44022.00000,7583.000000,82.0000,79.000000,36.000000,19.000000,19.000000,0.0,...,102.000000,196.000000,7.000000,0.0,54985.000000,35883.000000,53117.000000,869.000000,726.000000,42.000000

In [8]:
nan_values = df.isna().sum()
nan_columns = nan_values.any()
columns_with_nan = df.columns[nan_columns].tolist()
print(columns_with_nan)

[['ENRTOT', 'FTE', 'ENRFT', 'ENRPT', 'PCTENRWH', 'PCTENRBK', 'PCTENRHS', 'PCTENRAP', 'PCTENRAS', 'PCTENRNH', 'PCTENRAN', 'PCTENR2M', 'PCTENRUN', 'PCTENRNR', 'PCTENRW', 'PCTFT1ST', 'EFUG', 'EFUG1ST', 'EFUGTRN', 'EFUGCNT', 'EFUGNDG', 'EFUGFT', 'EFUG1SFT', 'EFUGTRFT', 'EFUGCNFT', 'EFUGNDFT', 'EFUGPT', 'EFUG1SPT', 'EFUGTRPT', 'EFUGCNPT', 'EFUGNDPT', 'PCUENRWH', 'PCUENRBK', 'PCUENRHS', 'PCUENRAP', 'PCUENRAS', 'PCUENRNH', 'PCUENRAN', 'PCUENR2M', 'PCUENRUN', 'PCUENRNR', 'PCUENRW', 'EFGRAD', 'EFGRADFT', 'EFGRADPT', 'PCGENRWH', 'PCGENRBK', 'PCGENRHS', 'PCGENRAP', 'PCGENRAS', 'PCGENRNH', 'PCGENRAN', 'PCGENR2M', 'PCGENRUN', 'PCGENRNR', 'PCGENRW', 'DVEF01', 'DVEF02', 'DVEF03', 'DVEF05', 'DVEF06', 'DVEF07', 'DVEF09', 'DVEF10', 'DVEF11', 'DVEF13', 'DVEF14', 'DVEF15', 'DVEF16', 'RMINSTTN', 'RMOUSTTN', 'RMFRGNCN', 'RMUNKNWN', 'RMINSTTP', 'RMOUSTTP', 'RMFRGNCP', 'RMUNKNWP', 'PCTDEEXC', 'PCTDESOM', 'PCTDENON', 'PCUDEEXC', 'PCUDESOM', 'PCUDENON', 'PCGDEEXC', 'PCGDESOM', 'PCGDENON', 'GRRTTOT', 'GRRTM', 'GRRTW', 'GRRTAN', 'GRRTAP', 'GRRTAS', 'GRRTBK', 'GRRTHS', 'GRRTWH', 'GRRTUN', 'GRRTNR', 'GBA4RTT', 'GBA5RTT', 'GBA6RTT', 'GBA6RTM', 'GBA6RTW', 'GBA6RTAN', 'GBA6RTAP', 'GBA6RTAS', 'GBA6RTBK', 'GBA6RTHS', 'GBA6RTWH', 'GBA6RTUN', 'GBA6RTNR', 'SALTOTL', 'SALPROF', 'SALASSC', 'SALASST', 'SALINST', 'SALLECT', 'SFTETOTL', 'SFTEPSTC', 'SFTEINST', 'SFTERSRC', 'SFTEPBSV', 'SFTELCAI', 'SFTELCA', 'SFTEOTIS', 'SFTEMNGM', 'SFTEBFO', 'SFTECES', 'SFTECLAM', 'SFTEHLTH', 'SFTEOTHR', 'SFTESRVC', 'SFTESALE', 'SFTEOFAS', 'SFTENRCM', 'SFTEPTMM', 'TUFEYR0', 'TUFEYR1', 'TUFEYR2', 'TUFEYR3', 'CINDON', 'CINSON', 'COTSON', 'CINDOFF', 'CINSOFF', 'COTSOFF', 'CINDFAM', 'CINSFAM', 'COTSFAM', 'F1CORREV', 'F1TUFEPC', 'F1STAPPC', 'F1LCAPPC', 'F1GVGCPC', 'F1PGGCPC', 'F1INVRPC', 'F1OTRVPC', 'F1TUFEFT', 'F1STAPFT', 'F1LCAPFT', 'F1GVGCFT', 'F1PGGCFT', 'F1INVRFT', 'F1OTRVFT', 'F1COREXP', 'F1INSTFT', 'F1RSRCFT', 'F1PBSVFT', 'F1ACSPFT', 'F1STSVFT', 'F1INSUFT', 'F1OTEXFT', 'F1INSTPC', 'F1RSRCPC', 'F1PBSVPC', 'F1ACSPPC', 'F1STSVPC', 'F1INSUPC', 'F1OTEXPC', 'F1ENDMFT', 'F1SAFBPC', 'F1SALRPC', 'F1EQUITR', 'ASCDEG', 'BASDEG', 'MASDEG', 'CERT1', 'CERT2', 'CERT4', 'PBACERT', 'PMACERT', 'SDOCDEG', 'SMASDEG', 'SBASDEG', 'SASCDEG', 'SBAMACRT', 'SCERT24', 'SCERT1', 'UNDUP', 'UNDUPUG', 'FTE12MN', 'DOCDEGRS', 'DOCDEGPP', 'DOCDEGOT']]

In [10]:
import statsmodels.api as sm
			
def stepwise_selection(X, y, 
                       initial_list=[], 
                       threshold_in=0.01, 
                       threshold_out = 0.05, 
                       verbose=True):
    """ Perform a forward-backward feature selection 
    based on p-value from statsmodels.api.OLS
    Arguments:
        X - pandas.DataFrame with candidate features
        y - list-like with the target
        initial_list - list of features to start with (column names of X)
        threshold_in - include a feature if its p-value < threshold_in
        threshold_out - exclude a feature if its p-value > threshold_out
        verbose - whether to print the sequence of inclusions and exclusions
    Returns: list of selected features 
    Always set threshold_in < threshold_out to avoid infinite looping.
    See https://en.wikipedia.org/wiki/Stepwise_regression for the details
    """
    included = list(initial_list)
    while True:
        changed=False
        # forward step
        excluded = list(set(X.columns)-set(included))
        new_pval = pd.Series(index=excluded)
        for new_column in excluded:
            model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included+[new_column]]))).fit()
            new_pval[new_column] = model.pvalues[new_column]
        best_pval = new_pval.min()
        if best_pval < threshold_in:
            best_feature = new_pval.idxmin()
            included.append(best_feature)
            changed=True
            #if verbose:
                #print('Add  {:30} with p-value {:.6}'.format(best_feature, best_pval))

        # backward step
        model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included]))).fit()
        # use all coefs except intercept
        pvalues = model.pvalues.iloc[1:]
        worst_pval = pvalues.max() # null if pvalues is empty
        if worst_pval > threshold_out:
            changed=True
            worst_feature = pvalues.argmax()
            included.remove(worst_feature)
            #if verbose:
                #print('Drop {:30} with p-value {:.6}'.format(worst_feature, worst_pval))
        if not changed:
            break
    included.append('id')
    print('resulting features:')
    print(included)
    
    return included

In [14]:
#set target graduation rates
y = df['F1CORREV']
X = df.drop(columns=['F1CORREV'], axis=1)
X

              ENRTOT      FTE    ENRFT   ENRPT  PCTENRWH  PCTENRBK  PCTENRHS  \
year UNITID
2018 145600  31683.0  28833.0  27117.0  4566.0      33.0       8.0      26.0
     149222  12817.0  11327.0  10386.0  2431.0      63.0      14.0       8.0
     149231  13281.0  11426.0  10253.0  3028.0      72.0      13.0       4.0
     149772   8502.0   7435.0   6778.0  1724.0      60.0      18.0      11.0
2017 145600  30539.0  27657.0  25927.0  4612.0      34.0       8.0      25.0
     149222  14554.0  12909.0  11877.0  2677.0      63.0      15.0       8.0
     149231  13796.0  11945.0  10775.0  3021.0      73.0      13.0       4.0
     149772   9441.0   8325.0   7631.0  1810.0      60.0      19.0      11.0
2016 145600  29120.0  26237.0  24509.0  4611.0      36.0       8.0      23.0
     149222  15987.0  14096.0  12918.0  3069.0      63.0      16.0       8.0
     149231  14142.0  12300.0  11137.0  3005.0      73.0      13.0       4.0
     149772  10373.0   9132.0   8360.0  2013.0      61.0      18.0      10.0
2015 145600  29048.0  26065.0  24283.0  4765.0      38.0       8.0      21.0
     149222  17292.0  15235.0  13960.0  3332.0      62.0      17.0       7.0
2014 145600  27969.0  25018.0  23263.0  4706.0      40.0       8.0      19.0
     149222  17989.0  15906.0  14621.0  3368.0      61.0      17.0       7.0
     149231  13972.0  12133.0  10979.0  2993.0      73.0      13.0       4.0
2013 145600  28038.0  25028.0  23239.0  4799.0      42.0       8.0      18.0
     149222  17964.0  15802.0  14478.0  3486.0      63.0      17.0       6.0
2012 145600  27875.0  24863.0  23071.0  4804.0      43.0       8.0      18.0
     149222  18847.0  16503.0  15061.0  3786.0      64.0      19.0       6.0
     149231  14055.0  12028.0  10768.0  3287.0      74.0      13.0       3.0

             PCTENRAP  PCTENRAS  PCTENRNH  ...  SASCDEG  SBAMACRT  SCERT24  \
year UNITID                                ...
2018 145600      18.0      18.0       0.0  ...      0.0      60.0      0.0
     149222       2.0       2.0       0.0  ...     97.0      10.0      0.0
     149231       3.0       2.0       0.0  ...      0.0      39.0      0.0
     149772       1.0       1.0       0.0  ...      0.0      47.0      0.0
2017 145600      19.0      19.0       0.0  ...      0.0      52.0      0.0
     149222       2.0       2.0       0.0  ...     91.0       6.0      0.0
     149231       2.0       2.0       0.0  ...      0.0      41.0      0.0
     149772       1.0       1.0       0.0  ...      0.0      50.0      0.0
2016 145600      19.0      19.0       0.0  ...      0.0      71.0      0.0
     149222       2.0       2.0       0.0  ...     91.0      10.0      0.0
     149231       2.0       2.0       0.0  ...      0.0      30.0      0.0
     149772       1.0       1.0       0.0  ...      0.0      72.0      0.0
2015 145600      19.0      18.0       0.0  ...      0.0      69.0      0.0
     149222       2.0       2.0       0.0  ...    102.0      12.0      0.0
2014 145600      19.0      19.0       0.0  ...      0.0      80.0      0.0
     149222       2.0       2.0       0.0  ...     79.0       4.0      0.0
     149231       2.0       2.0       0.0  ...      0.0      40.0      0.0
2013 145600      19.0      19.0       0.0  ...      0.0      69.0      0.0
     149222       2.0       2.0       0.0  ...     89.0       9.0      0.0
2012 145600      19.0      18.0       0.0  ...      0.0      61.0      0.0
     149222       2.0       2.0       0.0  ...     46.0       8.0      0.0
     149231       2.0       2.0       0.0  ...      0.0      49.0      0.0

             SCERT1    UNDUP  UNDUPUG  FTE12MN  DOCDEGRS  DOCDEGPP  DOCDEGOT
year UNITID
2018 145600     0.0  33386.0  21205.0  31098.0     349.0     726.0       0.0
     149222     0.0  16271.0  12170.0  13077.0     167.0     181.0       0.0
     149231     0.0  16021.0  12972.0  12245.0       1.0     126.0      42.0
     149772     0.0  10905.0   8599.0   8322.0      17.0       0.0       0.0
2017 145600     0.0  31879.0  19476.0  29320.0     370.0     692.0       0.0
     149222     0.0  17873.0  13518.0  14303.0     174.0     179.0       0.0
     149231     0.0  16432.0  13294.0  12622.0      10.0     129.0      10.0
     149772     0.0  11951.0   9656.0   9116.0      12.0       0.0       0.0
2016 145600     0.0  31848.0  19184.0  29227.0     346.0     705.0       0.0
     149222     0.0  19411.0  14593.0  16227.0     179.0     185.0       0.0
     149231     0.0  16467.0  13163.0  12681.0       6.0     130.0       8.0
     149772     0.0  12738.0  10355.0   9716.0      13.0       0.0       0.0
2015 145600     0.0  31123.0  18459.0  28352.0     314.0     676.0       0.0
     149222     0.0  20310.0  15116.0  16923.0     179.0     168.0       0.0
2014 145600     0.0  31015.0  18269.0  28263.0     328.0     641.0       0.0
     149222     0.0  19844.0  14779.0  16836.0     170.0     175.0       0.0
     149231     0.0  15879.0  12506.0  12296.0      10.0     129.0      14.0
2013 145600     0.0  31011.0  18270.0  28312.0     352.0     622.0       0.0
     149222     0.0  20675.0  15619.0  17355.0     148.0     206.0       0.0
2012 145600     0.0  31400.0  18698.0  28348.0     342.0     570.0       0.0
     149222     0.0  22536.0  17448.0  16910.0     162.0     196.0       0.0
     149231     0.0  16427.0  12773.0  12652.0       0.0     121.0       0.0

[22 rows x 202 columns]

In [12]:
stepwise_selection(X,y)

<ipython-input-10-59576973df7c>:26: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)
<ipython-input-10-59576973df7c>:26: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)
<ipython-input-10-59576973df7c>:26: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)
<ipython-input-10-59576973df7c>:26: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_pval = pd.Series(index=excluded)

ValueError: list.remove(x): x not in list

In [13]:
X.columns

Index(['ENRTOT', 'FTE', 'ENRFT', 'ENRPT', 'PCTENRWH', 'PCTENRBK', 'PCTENRHS',
       'PCTENRAP', 'PCTENRAS', 'PCTENRNH',
       ...
       'SASCDEG', 'SBAMACRT', 'SCERT24', 'SCERT1', 'UNDUP', 'UNDUPUG',
       'FTE12MN', 'DOCDEGRS', 'DOCDEGPP', 'DOCDEGOT'],
      dtype='object', length=202)